CREATE TABLE IF NOT EXISTS t_p98037960_adr_security_prototy.adr_templates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    icon TEXT NOT NULL DEFAULT 'FileText',
    source_adr_id TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'Предложено',
    jira_ticket TEXT NOT NULL DEFAULT '',
    product_name TEXT NOT NULL DEFAULT '',
    appeal_type TEXT NOT NULL DEFAULT 'Консультация',
    author TEXT NOT NULL DEFAULT '',
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    context TEXT NOT NULL DEFAULT '',
    decision TEXT NOT NULL DEFAULT '',
    consequences TEXT NOT NULL DEFAULT '',
    section_order JSONB NOT NULL DEFAULT '[]'::jsonb,
    section_layout JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);