CREATE TABLE t_p98037960_adr_security_prototy.adrs (
  id          TEXT PRIMARY KEY,
  number      INTEGER NOT NULL,
  title       TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'Предложено',
  jira_ticket TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  appeal_type TEXT NOT NULL DEFAULT 'Консультация',
  date        TEXT NOT NULL DEFAULT '',
  author      TEXT NOT NULL DEFAULT '',
  tags        JSONB NOT NULL DEFAULT '[]',
  context     TEXT NOT NULL DEFAULT '',
  decision    TEXT NOT NULL DEFAULT '',
  consequences TEXT NOT NULL DEFAULT '',
  section_order JSONB NOT NULL DEFAULT '[]',
  section_layout JSONB NOT NULL DEFAULT '[]',
  versions    JSONB NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
