FROM python:3.11-slim

WORKDIR /app

COPY backend/adr-templates/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/adr-templates/ .

EXPOSE 8001

CMD ["python", "server.py"]
